name: nflwin
dependencies:
- numpy=1.11.0
- pandas=0.18.0
- psycopg2=2.6.1
- pytest=2.9.1
- pytest-cov=2.2.1
- scikit-learn=0.17.1
- scipy=0.17.0
- sqlalchemy=1.0.12
- pip:
  - nfldb==0.2.15
  - nflgame==1.2.19

